name: Collect
on:
  schedule:
    - cron: "0 */3 * * *"   # every 3 hours
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

env:
  TZ: Asia/Shanghai
  GIST_PAT: ${{ secrets.GIST_PAT }}
  GIST_LINK: ${{ secrets.GIST_LINK }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  ENABLE_SPECIAL_PROTOCOLS: ${{ vars.ENABLE_SPECIAL_PROTOCOLS }}

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Prepare
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          architecture: "x64"
          cache: "pip"

      - name: Install
        run: pip3 install -r requirements.txt

      - name: Collect
        run: python -u subscribe/collect.py --all --refresh --skip

      - name: Commit data to repo
        run: |
          git config --local user.email 'liaoxin11@users.noreply.github.com'
          git config --local user.name 'liaoxin11'
          git add ./data/* || true
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S') sub_merge_node" || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.GIST_PAT }}

      - name: Timestamp
        run: date
